### PR TITLE
Update R-CMD-check.yaml

### PR DESCRIPTION
**Pull request by maelle**
just a try

### CODE REVIEW

**Comment by maelle** [comment]
@rempsyc I was wondering whether the error could be solved by updating the cache (locally I don't get any error either)

**Comment by maelle** [comment]
interesting that it fails only on two OS now! I wonder if there is some dependency with a new version whose binaries are not available yet (no binary on Ubuntu anyway)

**Comment by rempsyc** [comment]
First, thanks Maëlle for helping out on this! :D

Second, it was already these two OS (macOS and Windows) only that were failing before, on multiple attempts: https://github.com/rempsyc/lavaanExtra/actions

I will try to isolate the chunks as suggested by Gabor.

**Comment by maelle** [comment]
aaah interesting! and locally I was using Ubuntu so not very helpful then :sweat_smile: Good luck!

**Comment by rempsyc** [comment]
Interestingly, I _am_ on Windows and there is no error/warning/note either on my setup 🙃

**Pull request closed without merging**
